#!/usr/bin/env python3
"""
Find True f₀: The Seed Frequency of the Inhibitory φ-Lattice
=============================================================

If the trough lattice is generated by Fibonacci recurrence from a seed
frequency f₀, then all trough positions should satisfy:

    T_n = f₀ × φ^n  for integer n

This script finds the f₀ that best fits the observed trough positions,
using multiple approaches:

1. Least-squares in log space: minimize Σ(log(T_n) - log(f₀) - n·log(φ))²
2. Free-ratio fit: fit both f₀ and r simultaneously
3. Period concatenation consistency: find f₀ where T_i + T_j = T_k
4. Per-bootstrap-sample f₀ estimation
5. Per-subject f₀ estimation (from individual trough depths)

Usage:
    python scripts/find_true_f0.py

Outputs to: outputs/f0_estimation/
"""

import os
import numpy as np
import pandas as pd
from scipy.optimize import minimize_scalar, minimize
from scipy import stats

BASE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT_DIR = os.path.join(BASE_DIR, 'outputs', 'f0_estimation')

PHI = (1 + np.sqrt(5)) / 2

# Bootstrap trough positions (medians)
TROUGHS = np.array([5.0274, 7.8227, 13.5949, 24.7516, 34.3834])
TROUGH_LABELS = ['δ/θ', 'θ/α', 'α/β', 'βL/βH', 'βH/γ']

# Bootstrap CIs
TROUGH_CI_LO = np.array([4.98, 7.82, 13.40, 24.25, 34.18])
TROUGH_CI_HI = np.array([5.13, 7.85, 13.83, 26.01, 34.79])

# KDE positions (alternative)
TROUGHS_KDE = np.array([5.15, 7.77, 13.43, 25.29, 35.24])

BOOTSTRAP_GEO_PATH = os.path.join(BASE_DIR, 'outputs', 'bootstrap_troughs', 'bootstrap_geo_means.csv')
PER_SUBJECT_PATH = os.path.join(BASE_DIR, 'outputs', 'trough_depth_by_age', 'per_subject_trough_depths.csv')


def approach_1_log_least_squares():
    """Find f₀ by fitting T_n = f₀ × φ^n in log space."""
    print("\n--- Approach 1: Log-Space Least Squares (ratio fixed at φ) ---")

    # For each candidate assignment of integer n to each trough,
    # find the best f₀.
    # The natural assignment: n = -1, 0, 1, 2, 3 (with θ/α = n=0)

    log_phi = np.log(PHI)
    log_troughs = np.log(TROUGHS)

    assignments = [
        ('n = -1,0,1,2,3', np.array([-1, 0, 1, 2, 3])),
        ('n = -1,0,1,2,3 (skip bridge)', np.array([-1, 0, 1, 2, 3])),  # will weight
    ]

    results = []

    for label, ns in assignments:
        # log(T_n) = log(f₀) + n × log(φ)
        # This is linear regression: y = a + b×x with b fixed at log(φ)
        # Residuals: r_n = log(T_n) - n × log(φ) - log(f₀)
        # Optimal log(f₀) = mean(log(T_n) - n × log(φ))

        residuals_from_phi = log_troughs - ns * log_phi
        log_f0 = np.mean(residuals_from_phi)
        f0 = np.exp(log_f0)

        # Compute fit quality
        predicted_log = log_f0 + ns * log_phi
        predicted_hz = np.exp(predicted_log)
        errors_hz = TROUGHS - predicted_hz
        errors_pct = errors_hz / TROUGHS * 100
        rmse_log = np.sqrt(np.mean((log_troughs - predicted_log)**2))
        rmse_hz = np.sqrt(np.mean(errors_hz**2))

        print(f"\n  {label}")
        print(f"  f₀ = {f0:.4f} Hz")
        print(f"  RMSE (log): {rmse_log:.6f}, RMSE (Hz): {rmse_hz:.4f}")
        print(f"  {'Trough':<10} {'Observed':>10} {'Predicted':>10} {'Error (Hz)':>12} {'Error (%)':>10}")
        for i, (tl, obs, pred, err, epct) in enumerate(
                zip(TROUGH_LABELS, TROUGHS, predicted_hz, errors_hz, errors_pct)):
            print(f"  {tl:<10} {obs:>10.4f} {pred:>10.4f} {err:>+12.4f} {epct:>+10.2f}%")

        results.append({
            'method': label, 'f0': f0, 'ratio': PHI,
            'rmse_log': rmse_log, 'rmse_hz': rmse_hz,
        })

    # Also try with different n-assignments
    # What if θ/α isn't n=0? Try all reasonable assignments
    print("\n  --- Scanning all n-offset assignments ---")
    best_rmse = np.inf
    best_offset = None
    best_f0 = None

    for offset in np.arange(-3, 4, 1):
        ns = np.array([-1, 0, 1, 2, 3]) + offset
        residuals = log_troughs - ns * log_phi
        log_f0 = np.mean(residuals)
        predicted = log_f0 + ns * log_phi
        rmse = np.sqrt(np.mean((log_troughs - predicted)**2))
        f0 = np.exp(log_f0)
        print(f"  offset={offset:+d}, n={ns}, f₀={f0:.4f} Hz, RMSE={rmse:.6f}")

        if rmse < best_rmse:
            best_rmse = rmse
            best_offset = offset
            best_f0 = f0

    print(f"\n  Best: offset={best_offset}, f₀={best_f0:.4f} Hz")
    return best_f0


def approach_2_free_ratio():
    """Fit both f₀ and r simultaneously."""
    print("\n--- Approach 2: Free f₀ and r (both parameters free) ---")

    log_troughs = np.log(TROUGHS)
    ns = np.array([-1, 0, 1, 2, 3])

    def objective(params):
        log_f0, log_r = params
        predicted = log_f0 + ns * log_r
        return np.sum((log_troughs - predicted)**2)

    # Grid search for initial guess
    best = (np.inf, 0, 0)
    for f0_try in np.arange(6.0, 10.0, 0.1):
        for r_try in np.arange(1.3, 2.0, 0.01):
            val = objective([np.log(f0_try), np.log(r_try)])
            if val < best[0]:
                best = (val, f0_try, r_try)

    result = minimize(objective, [np.log(best[1]), np.log(best[2])], method='Nelder-Mead')
    f0_opt = np.exp(result.x[0])
    r_opt = np.exp(result.x[1])

    predicted = np.exp(result.x[0] + ns * result.x[1])
    errors = TROUGHS - predicted
    errors_pct = errors / TROUGHS * 100

    print(f"  f₀ = {f0_opt:.4f} Hz, r = {r_opt:.6f}")
    print(f"  φ = {PHI:.6f}, |r - φ| = {abs(r_opt - PHI):.6f}")
    print(f"  {'Trough':<10} {'Observed':>10} {'Predicted':>10} {'Error (Hz)':>12} {'Error (%)':>10}")
    for tl, obs, pred, err, epct in zip(TROUGH_LABELS, TROUGHS, predicted, errors, errors_pct):
        print(f"  {tl:<10} {obs:>10.4f} {pred:>10.4f} {err:>+12.4f} {epct:>+10.2f}%")

    rmse = np.sqrt(np.mean(errors**2))
    print(f"  RMSE: {rmse:.4f} Hz")

    # Compare: fix r=φ, only fit f₀
    def obj_phi(log_f0):
        predicted = log_f0 + ns * np.log(PHI)
        return np.sum((log_troughs - predicted)**2)

    res_phi = minimize_scalar(obj_phi, bounds=(np.log(5), np.log(12)), method='bounded')
    f0_phi = np.exp(res_phi.x)
    pred_phi = np.exp(res_phi.x + ns * np.log(PHI))
    rmse_phi = np.sqrt(np.mean((TROUGHS - pred_phi)**2))

    print(f"\n  With r fixed at φ: f₀ = {f0_phi:.4f} Hz, RMSE = {rmse_phi:.4f}")
    print(f"  With r free:       f₀ = {f0_opt:.4f} Hz, RMSE = {rmse:.4f}")
    print(f"  Improvement from freeing r: {(rmse_phi - rmse):.4f} Hz ({(rmse_phi-rmse)/rmse_phi*100:.1f}%)")

    return f0_opt, r_opt, f0_phi


def approach_3_period_concatenation():
    """Find f₀ from period concatenation consistency."""
    print("\n--- Approach 3: Period Concatenation Consistency ---")
    print("  If T_i + T_j = T_k (Fibonacci), what f₀ makes this most consistent?\n")

    # Fibonacci-adjacent triples from the lattice:
    # T(n-1) + T(n) = T(n+1) means:
    #   f₀φ^(n-1) + f₀φ^n = f₀φ^(n+1)
    #   which is always true since φ^(n-1) + φ^n = φ^(n+1)
    #
    # But the OBSERVED troughs may not satisfy this exactly.
    # For each consecutive triple, compute f₀ = T(n+1) / φ^(n+1)
    # and check: T(n-1) + T(n) vs T(n+1)

    ns = np.array([-1, 0, 1, 2, 3])

    print("  Period concatenation sums (observed):")
    triples = [
        ('T1+T2→T3', 0, 1, 2),  # δ/θ + θ/α → α/β
        ('T2+T3→T4', 1, 2, 3),  # θ/α + α/β → βL/βH
        ('T3+T4→T5', 2, 3, 4),  # α/β + βL/βH → βH/γ
    ]

    for label, i, j, k in triples:
        sum_ij = TROUGHS[i] + TROUGHS[j]
        observed_k = TROUGHS[k]
        error = sum_ij - observed_k
        error_pct = error / observed_k * 100
        print(f"  {label}: {TROUGHS[i]:.2f} + {TROUGHS[j]:.2f} = {sum_ij:.2f}, "
              f"observed T{k+1} = {observed_k:.2f}, Δ = {error:+.2f} Hz ({error_pct:+.1f}%)")

    # Each triple gives an independent f₀ estimate:
    # T(n+1) = f₀ × φ^(n+1), so f₀ = T(n+1) / φ^(n+1)
    print("\n  Per-trough f₀ estimates (from T_n = f₀ × φ^n):")
    f0_estimates = []
    for i, (label, t, n) in enumerate(zip(TROUGH_LABELS, TROUGHS, ns)):
        f0_est = t / PHI**n
        f0_estimates.append(f0_est)
        print(f"  {label} (n={n:+d}): f₀ = {t:.4f} / φ^{n} = {f0_est:.4f} Hz")

    f0_mean = np.mean(f0_estimates)
    f0_median = np.median(f0_estimates)
    f0_sd = np.std(f0_estimates)
    print(f"\n  Mean f₀: {f0_mean:.4f} ± {f0_sd:.4f} Hz")
    print(f"  Median f₀: {f0_median:.4f} Hz")

    # The spread tells us how self-consistent the lattice is
    print(f"  CV: {f0_sd/f0_mean*100:.2f}%")
    print(f"  Range: [{min(f0_estimates):.4f}, {max(f0_estimates):.4f}]")

    # Which trough is most consistent with the mean f₀?
    print(f"\n  Residuals from mean f₀ = {f0_mean:.4f}:")
    for label, est in zip(TROUGH_LABELS, f0_estimates):
        print(f"    {label}: {est - f0_mean:+.4f} Hz")

    return f0_estimates


def approach_4_weighted_fit():
    """Weight troughs by their bootstrap CI precision."""
    print("\n--- Approach 4: Precision-Weighted f₀ (by bootstrap CI width) ---")

    ns = np.array([-1, 0, 1, 2, 3])
    log_troughs = np.log(TROUGHS)
    log_phi = np.log(PHI)

    # Weights: inverse of CI width (tighter CI = higher weight)
    ci_widths = TROUGH_CI_HI - TROUGH_CI_LO
    # In log space
    log_ci_widths = np.log(TROUGH_CI_HI) - np.log(TROUGH_CI_LO)
    weights = 1.0 / log_ci_widths
    weights /= weights.sum()

    print(f"  CI widths (Hz): {ci_widths}")
    print(f"  Weights: {weights.round(4)}")

    # Weighted mean of log(T_n) - n × log(φ)
    residuals = log_troughs - ns * log_phi
    log_f0_weighted = np.average(residuals, weights=weights)
    f0_weighted = np.exp(log_f0_weighted)

    # Unweighted for comparison
    log_f0_unweighted = np.mean(residuals)
    f0_unweighted = np.exp(log_f0_unweighted)

    predicted_w = np.exp(log_f0_weighted + ns * log_phi)
    predicted_u = np.exp(log_f0_unweighted + ns * log_phi)

    print(f"\n  Unweighted f₀: {f0_unweighted:.4f} Hz")
    print(f"  Weighted f₀:   {f0_weighted:.4f} Hz")
    print(f"  Difference:     {f0_weighted - f0_unweighted:+.4f} Hz")

    print(f"\n  θ/α trough (most precise, CI = {ci_widths[1]:.3f} Hz) gets weight {weights[1]:.3f}")
    print(f"  βL/βH trough (least precise, CI = {ci_widths[3]:.3f} Hz) gets weight {weights[3]:.3f}")

    # The θ/α trough at 7.8227 Hz with n=0 gives f₀ = 7.8227 directly.
    # Its weight is very high due to tight CI.
    # So the weighted f₀ should be pulled toward 7.82.
    print(f"\n  Per-trough f₀ implied (T_n / φ^n):")
    for label, t, n, w in zip(TROUGH_LABELS, TROUGHS, ns, weights):
        f0_impl = t / PHI**n
        print(f"    {label} (w={w:.3f}): {f0_impl:.4f} Hz")

    return f0_weighted


def approach_5_excluding_bridge():
    """Fit f₀ excluding βL/βH (bridge may not be a true trough)."""
    print("\n--- Approach 5: f₀ Excluding βL/βH (Bridge) ---")

    # The bridge at ~25 Hz is the weakest trough (11.6% depletion)
    # and has the widest CI (1.75 Hz). It may be a failed wall,
    # shifted from its ideal position by motor enrichment.
    # What f₀ do we get without it?

    mask = np.array([True, True, True, False, True])  # exclude βL/βH
    troughs_4 = TROUGHS[mask]
    ns_4 = np.array([-1, 0, 1, 3])  # skip n=2

    log_troughs_4 = np.log(troughs_4)
    log_phi = np.log(PHI)

    residuals = log_troughs_4 - ns_4 * log_phi
    log_f0 = np.mean(residuals)
    f0 = np.exp(log_f0)

    predicted = np.exp(log_f0 + np.array([-1, 0, 1, 2, 3]) * log_phi)
    errors = TROUGHS - predicted

    print(f"  f₀ (4 troughs, excl βL/βH) = {f0:.4f} Hz")
    print(f"  {'Trough':<10} {'Observed':>10} {'Predicted':>10} {'Error':>12} {'Note':>15}")
    labels_all = TROUGH_LABELS
    for i, (label, obs, pred, err) in enumerate(zip(labels_all, TROUGHS, predicted, errors)):
        note = '(excluded)' if label == 'βL/βH' else ''
        print(f"  {label:<10} {obs:>10.4f} {pred:>10.4f} {err:>+12.4f} {note:>15}")

    # Where does this f₀ predict the bridge should be?
    bridge_predicted = f0 * PHI**2
    bridge_observed = TROUGHS[3]
    print(f"\n  Bridge predicted by this f₀: {bridge_predicted:.2f} Hz")
    print(f"  Bridge observed: {bridge_observed:.2f} Hz")
    print(f"  Shift: {bridge_observed - bridge_predicted:+.2f} Hz")
    print(f"  (Positive = bridge is pulled upward from ideal wall position)")

    return f0


def approach_6_bootstrap_f0():
    """Estimate f₀ from each bootstrap sample's trough positions."""
    print("\n--- Approach 6: Bootstrap f₀ Distribution ---")

    if not os.path.exists(BOOTSTRAP_GEO_PATH):
        print("  Bootstrap geo means file not found")
        return None

    # We have bootstrap geo means but not per-sample trough positions.
    # Use the geo mean to back-compute f₀.
    geo_means = pd.read_csv(BOOTSTRAP_GEO_PATH)['boot_geo_mean'].values
    print(f"  {len(geo_means)} bootstrap samples")
    print(f"  Geo mean ratio: {np.mean(geo_means):.6f} ± {np.std(geo_means):.6f}")

    # For each bootstrap geo mean r, the lattice is T_n = f₀ × r^n
    # Using θ/α trough (most stable) as anchor: f₀ = T_θα / r^0 = T_θα
    # So f₀ = θ/α trough position in each bootstrap sample.
    # Since we don't have per-sample positions, we can only note:
    print(f"  θ/α trough CI: [{TROUGH_CI_LO[1]:.4f}, {TROUGH_CI_HI[1]:.4f}]")
    print(f"  If θ/α IS f₀, then f₀ ∈ [{TROUGH_CI_LO[1]:.4f}, {TROUGH_CI_HI[1]:.4f}]")
    print(f"  CI width: {TROUGH_CI_HI[1] - TROUGH_CI_LO[1]:.4f} Hz")

    return None


def summary(f0_ls, f0_free, r_free, f0_phi, f0_weighted, f0_excl_bridge, f0_per_trough):
    """Summarize all f₀ estimates."""
    print("\n" + "=" * 70)
    print("SUMMARY: f₀ Estimates")
    print("=" * 70)

    estimates = {
        'Log-LS (r=φ)': f0_ls,
        'Free r fit': f0_free,
        'Precision-weighted': f0_weighted,
        'Excluding bridge': f0_excl_bridge,
        'Per-trough mean': np.mean(f0_per_trough),
        'Per-trough median': np.median(f0_per_trough),
        'θ/α trough direct': TROUGHS[1],
        'Paper coordinate f₀': 7.60,
    }

    print(f"\n  {'Method':<30} {'f₀ (Hz)':>10}")
    print("  " + "-" * 45)
    for method, f0 in estimates.items():
        print(f"  {method:<30} {f0:>10.4f}")

    vals = [v for k, v in estimates.items() if k != 'Paper coordinate f₀']
    print(f"\n  Cross-method mean:   {np.mean(vals):.4f} Hz")
    print(f"  Cross-method median: {np.median(vals):.4f} Hz")
    print(f"  Cross-method range:  [{min(vals):.4f}, {max(vals):.4f}]")

    print(f"\n  Key reference points:")
    print(f"    θ/α trough (bootstrap median):  7.8227 Hz")
    print(f"    θ/α trough (bootstrap CI):      [7.8227, 7.8455]")
    print(f"    Paper coordinate f₀:            7.6000 Hz")
    print(f"    SR1 nominal:                    7.83 Hz")

    # The two f₀ values serve different purposes:
    print(f"\n  Interpretation:")
    print(f"    The 'true' f₀ (lattice seed) ≈ {np.median(vals):.2f} Hz")
    print(f"    The coordinate f₀ = 7.60 Hz optimizes enrichment measurement")
    print(f"    These differ because the lattice is not perfectly rigid --")
    print(f"    biological constraints shift walls from their ideal φ^n positions.")
    print(f"    The coordinate system absorbs these shifts into a lower f₀.")

    # Compute what the free-r fit tells us
    print(f"\n  Free ratio fit: r = {r_free:.6f} (φ = {PHI:.6f})")
    print(f"  Δr = {r_free - PHI:+.6f} ({(r_free-PHI)/PHI*100:+.3f}%)")
    if abs(r_free - PHI) < 0.01:
        print(f"  → Ratio is indistinguishable from φ to 2 decimal places")

    # Save
    df = pd.DataFrame([
        {'method': k, 'f0_hz': v} for k, v in estimates.items()
    ])
    df.to_csv(os.path.join(OUT_DIR, 'f0_estimates.csv'), index=False)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    print("=" * 70)
    print("Finding the True f₀: Seed Frequency of the Inhibitory φ-Lattice")
    print("=" * 70)

    f0_ls = approach_1_log_least_squares()
    f0_free, r_free, f0_phi = approach_2_free_ratio()
    f0_per_trough = approach_3_period_concatenation()
    f0_weighted = approach_4_weighted_fit()
    f0_excl_bridge = approach_5_excluding_bridge()
    approach_6_bootstrap_f0()

    summary(f0_ls, f0_free, r_free, f0_phi, f0_weighted, f0_excl_bridge, f0_per_trough)

    print(f"\nResults saved to {OUT_DIR}/")


if __name__ == '__main__':
    main()
